### USER REGISTRATION
POST http://localhost:8005/users/register
Content-Type: application/json

{
    "id" : 1,
    "firstName": "Jenna",
    "lastName": "Doney",
    "email": "jenna@gmail.com",
    "password" : "12345678"
}

### LOGIN
POST http://localhost:8005/users/login
Content-Type: application/json

{
    "email": "jenna@gmail.com",
    "password" : "12345678"
}


